
[[thisMod]]
Name = "The Sith Lords Restored Content Mod 2022"
Guid = "{d2bf7bbb-4757-4418-96bf-a9772a36a262}"
InstallOrder = "0"
Dependencies = []
Author = "zbyl2, DarthStoney, Hassat Hunter & VarsityPuppet"
Directions = "Executable. Recall that M4-78 is incompatible with this build; do not use it alongside TSLRCM! Remember also that the Workshop version of this or any other mod is NOT to be used!"
Description = "The whole reason why you would mod KOTOR 2, the legendary mod that includes bugfixes, restored content, and altered scenes to return the game to what it was meant to be. This mod isn't just essential--it's mandatory."
Language = ["All"]
Category = "Essential"

[[thisMod.Instructions]]
Action = "execute"
Source = ["<<modDirectory>>/tslrcm2022.exe"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "False"


[[thisMod]]
Name = "TSLRCM Tweak Pack"
Guid = "{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"
InstallOrder = "1"
Dependencies = ["{d2bf7bbb-4757-4418-96bf-a9772a36a262}"]
Directions = "Don't use the complete installer, instead select the individual component installer--this is critical for compatibility, not just to choose specific options. The installer for this mod will need to be run 7 times, once to install each of the options we'll be using: Kaevee Removal Parts 1 & 2, Saedhe's Head, Atton at the End, Kreia-Atris Dialogue Tweak, Trayus Mandalore Conversation, and Trayus Sith Lord Masks."
Description = "Reverts and otherwise modifies certain TSLRCM settings to make the game more sensible and internally consistent (mostly unrestoring content which was likely intentionally cut by Obsidian). This includes removing Jedi Padawan Kaevee."

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>\\URCMTP 1.3.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "tslpatcher"
Source = ["<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "False"
Arguments = ""


[[thisMod]]
Name = "Prestige Class Saving Throw Fixes"
Guid = "{3B2EA056-38F7-46D6-9E73-9041A0405B80}"
InstallOrder = "0"
Dependencies = []
Author = "Rovan"
Tier = "Recommended"
Description = "For some reason, some prestige classes in KOTOR 2 have worse saving throws than their predecessor class. This mod fixes this, ensuring that the more advanced classes always have slightly better throws."
Category = "Mechanics Change"

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/TSL_prestige_save_fixes.zip"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/TSL_prestige_save_fixes/TSL_prestige_save_fixes/jedimaster_sithlord fixes/*"]
Destination = "<<kotorDirectory>>/Override"
Dependencies = ["{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"]
Overwrite = "True"


[[thisMod]]
Name = "Robes with Shadows for TSL"
Guid = "{F2C74B45-7D85-4F56-96E9-61288CE4B78F}"
InstallOrder = "0"
Author = "PapaZinos"
Tier = "Suggested"
Directions = "Extract the mod. Ignore the included subfolders, and move just the files in the base folder to your override. Overwrite when prompted."
Description = "What use, I ask you, is the Soft Shadows setting ingame if your shadows are still 10 polygons? This mod gives all robes proper shadows that match their models more directly, for that extra touch of realism."
Language = ["All"]
Category = "Graphics Improvement"

[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/Ultimate_Robes_Repair_For_TSL*/*.*"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"


[[thisMod]]
Name = "K2 Community Patch"
Guid = "{6777F8ED-8978-49A0-ACE2-3005EFCF1DCF}"
InstallOrder = "0"
Dependencies = ["{d2bf7bbb-4757-4418-96bf-a9772a36a262}"]
Author = "Multiple; A Future Pilot, DarthParametric and JCarter426 Curate"
Tier = "Essential"
Directions = "Run the TSLPatcher exe included. Remember, warnings during an installation are normal--errors are not."
Description = "A community bugfix and general improvement patch for KOTOR 2 meant to be a supplement to TSLRCM, fixing bugs that TSLRCM didn't catch or viewed too minor to address; highly recommended."
Language = ["All"]
Category = "Graphics Improvement & Bugfix"

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/KOTOR 2 Community Patch*.7z"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"


[[thisMod]]
Name = "Remote Tells Influence"
Guid = "{8E737754-7A36-4A90-B9F2-0E92B834CFAA}"
InstallOrder = "0"
Dependencies = []
Author = "tk102, patch by Leilukin"
Tier = "Optional"
Description = "This is going to require a bit of an explanation. I personally believe this mod breaks immersion--so why add it? The bottom-line is that KOTOR 2's influence system is asinine, and major plot points are locked behind very high--or very low--influence with several companions. Your influence with companions is also extremely obfuscated, only really discernible by their LS/DS alignment relative to your alignment, but this is a very buggy system which breaks with high Charisma values on the player, or with certain feats. There is no other way ingame to tell what your influence is without this mod. I mark it as optional because it does break immersion, but for many players I think having a system to determine influence will be extremely important for enjoyment of the story."
Category = "Mechanics Change"

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/remote_influence.zip"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>\\remote_influence\remote.dlg", "<<modDirectory>>\\remote_influence\tk_remote_getinf.ncs"]
Destination = "<<kotorDirectory>>\\Override"
Overwrite = "False"
[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/Remote Tells Influence Patch for TSLRCM.zip"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/Remote Tells Influence Patch for TSLRCM/remote.dlg"]
Destination = "<<kotorDirectory>>\\Override"
Overwrite = "False"


[[thisMod]]
Name = "Ultimate HR Textures"
Guid = "{70547401-7188-4904-AC8C-819BD64AB257}"
InstallOrder = "3"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/Ultimate High Resolution Texture Pack - TPC Version*.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "delete"
Source = ["<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock02.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock03.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock04.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock05.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock06.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_rock07.tpc", "<<modDirectory>>\\High Resolution Texture Pack\\Override\\TEL_wl05.tpc"]
Destination = "<<kotorDirectory>>/Override"
Dependencies = []
Overwrite = "False"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/High Resolution Texture Pack/Override/*"]
Destination = "<<kotorDirectory>>\\Override"
Overwrite = "False"


[[thisMod]]
Name = "Ultimate Character Overhaul"
Guid = "{557CB2E9-BD8F-40E9-AA8D-FEAAA5FF4C94}"
InstallOrder = "3"
Dependencies = []
Author = "ShiningRedHD"
Tier = "Essential"
Description = "Ultimate Character Overhaul is a comprehensive AI-upscale of every character and piece of equipment in the game. Unlike previous AI upscales, the Ultimate series has no transparency problems while still retaining reflections on character textures, all without any additional steps required. This is an incredibly high-quality mod, and ShiningRed has even gone through the trouble to make compatibility patches for the mod builds, upscaling some of the later textures we use!"
Category = "Graphics Improvement"

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/Ultimate Character Overhaul*TPC Version*.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>\\Ultimate Character Overhaul*TPC Version*\\KOTORII - Ultimate Character Overhaul\\*"]
Destination = "<<kotorDirectory>>/Override"
Dependencies = []
Overwrite = "False"


[[thisMod]]
Name = "Ultimate Nar Shaddaa"
Guid = "{DDE36C80-0BD9-48F9-818C-82EF46507E48}"
InstallOrder = "3"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/Ultimate Nar Shaddaa High Resolution*TPC Version*.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "delete"
Source = ["<<modDirectory>>\\Nar Shaddaa HR\\Override\\NAR_wl07.tpc", "<<modDirectory>>\\Nar Shaddaa HR\\Override\\NAR_fl01.tpc", "<<modDirectory>>\\Nar Shaddaa HR\\Override\\NAR_Met4.tpc"]
Destination = "<<kotorDirectory>>/Override"
Dependencies = ["{}"]
Overwrite = "False"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/Nar Shaddaa HR/Override/*"]
Destination = "<<kotorDirectory\\Override"
Restrictions = ["{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"]
Overwrite = "False"


[[thisMod]]
Name = "Ultimate Dantooine"
Guid = "{B3525945-BDBD-45D8-A324-AAF328A5E13E}"
InstallOrder = "3"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["Ultimate Dantooine High Resolution*TPC Version*.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "delete"
Source = ["<<kotorDirectory>>/Ultimate Dantooine High Resolution*TPC Version*/DAN_wall03.tpc", "<<kotorDirectory>>/Ultimate Dantooine High Resolution*TPC Version*/DAN_NEW1.tpc", "<<kotorDirectory>>/Ultimate Dantooine High Resolution*TPC Version*/DAN_MWFl.tpc"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "False"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<kotorDirectory>>/Ultimate Dantooine High Resolution*TPC Version*/Dantooine HR/Override/*"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "False"


[[thisMod]]
Name = "Ultimate Dxun"
Guid = "{9E749DD5-BE68-4E63-B79F-4E95BB7674CA}"
InstallOrder = "0"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/path/to/mod/mod.rar"]
Destination = "<<kotorDirectory>>/Override"
Overwrite = "True"
[[thisMod.Instructions]]
Action = "delete"
Source = ["<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa1.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa2.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa3.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa4.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa5.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa6.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa7.tpc", "<<modDirectory>>\\Ultimate Dxun High Resolution*TPC Version*\\Dxun HR\\Override\\DXN_BWa8.tpc"]
Destination = "<<kotorDirectory>>/Override"
Dependencies = ["{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"]
Overwrite = "False"

