
[[thisMod]]
Name = "The Sith Lords Restored Content Mod 2022"
Guid = "{d2bf7bbb-4757-4418-96bf-a9772a36a262}"
InstallOrder = "0"
Dependencies = []
Author = "zbyl2, DarthStoney, Hassat Hunter & VarsityPuppet"
Directions = "Executable. Recall that M4-78 is incompatible with this build; do not use it alongside TSLRCM! Remember also that the Workshop version of this or any other mod is NOT to be used!"
Description = "The whole reason why you would mod KOTOR 2, the legendary mod that includes bugfixes, restored content, and altered scenes to return the game to what it was meant to be. This mod isn't just essential--it's mandatory."
Language = ["All"]
Category = "Essential"

[[thisMod.Instructions]]
Action = "execute"
Source = ["<<modDirectory>>/tslrcm2022.exe"]
Overwrite = "False"


[[thisMod]]
Name = "TSLRCM Tweak Pack"
Guid = "{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"
InstallOrder = "1"
Dependencies = ["{d2bf7bbb-4757-4418-96bf-a9772a36a262}"]
Directions = "Don't use the complete installer, instead select the individual component installer--this is critical for compatibility, not just to choose specific options. The installer for this mod will need to be run 7 times, once to install each of the options we'll be using: Kaevee Removal Parts 1 & 2, Saedhe's Head, Atton at the End, Kreia-Atris Dialogue Tweak, Trayus Mandalore Conversation, and Trayus Sith Lord Masks."
Description = "Reverts and otherwise modifies certain TSLRCM settings to make the game more sensible and internally consistent (mostly unrestoring content which was likely intentionally cut by Obsidian). This includes removing Jedi Padawan Kaevee."

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>\\URCMTP 1.3.rar"]
Overwrite = "True"
[[thisMod.Instructions]]
Action = "tslpatcher"
Source = ["<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe", "<<modDirectory>>\\URCMTP 1.3\\Individual component installer\\U_TSLRCM_TP_IND.exe"]
Overwrite = "False"
Arguments = ""


[[thisMod]]
Name = "Prestige Class Saving Throw Fixes"
Guid = "{0db2c43f-5298-4345-9e17-22852e64d3b7}"
InstallOrder = "0"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/TSL_prestige_save_fixes.zip"]
Overwrite = "True"
[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/TSL_prestige_save_fixes/TSL_prestige_save_fixes/jedimaster_sithlord fixes/*"]
Dependencies = ["{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"]
Overwrite = "True"


[[thisMod]]
Name = "Robes with Shadows for TSL"
Guid = "{F2C74B45-7D85-4F56-96E9-61288CE4B78F}"
InstallOrder = "0"
Author = "PapaZinos"
Directions = "Extract the mod. Ignore the included subfolders, and move just the files in the base folder to your override. Overwrite when prompted."
Description = "What use, I ask you, is the Soft Shadows setting ingame if your shadows are still 10 polygons? This mod gives all robes proper shadows that match their models more directly, for that extra touch of realism."
Language = ["All"]
Category = "Graphics Improvement"

[[thisMod.Instructions]]
Action = "move"
Source = ["<<modDirectory>>/Ultimate_Robes_Repair_For_TSL*/*.*"]
Overwrite = "True"


[[thisMod]]
Name = "K2 Community Patch"
Guid = "{6777F8ED-8978-49A0-ACE2-3005EFCF1DCF}"
InstallOrder = "0"
Dependencies = ["{d2bf7bbb-4757-4418-96bf-a9772a36a262}"]
Author = "Multiple; A Future Pilot, DarthParametric and JCarter426 Curate"
Tier = "Essential"
Directions = "Run the TSLPatcher exe included. Remember, warnings during an installation are normal--errors are not."
Description = "A community bugfix and general improvement patch for KOTOR 2 meant to be a supplement to TSLRCM, fixing bugs that TSLRCM didn't catch or viewed too minor to address; highly recommended."
Language = ["All"]
Category = "Graphics Improvement & Bugfix"

[[thisMod.Instructions]]
Action = "extract"
Source = ["<<modDirectory>>/KOTOR 2 Community Patch*.7z"]
Overwrite = "True"


[[thisMod]]
Name = "Ultimate Dantooine"
Guid = "{B3525945-BDBD-45D8-A324-AAF328A5E13E}"
InstallOrder = "3"
Dependencies = []

[[thisMod.Instructions]]
Action = "extract"
Source = ["Ultimate Dantooine High Resolution - TPC Version-1103-2-1-1670680013.rar"]
Overwrite = "True"
[[thisMod.Instructions]]
Action = "delete"
Overwrite = "False"
[[thisMod.Instructions]]
Action = "move"
Source = ["%temp%/mod_files/Dantooine HR"]
Overwrite = "False"

