[[thisMod]]
name = "Ultimate Dantooine"
guid = "{B3525945-BDBD-45D8-A324-AAF328A5E13E}"
dependencies = [
    "{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}",
    "{D0F371DA-5C69-4A26-8A37-76E3A6A2A50D}"
]
installOrder = 3

[[thisMod.instructions]]
action = "extract"
source = "Ultimate Dantooine High Resolution - TPC Version-1103-2-1-1670680013.rar"
destination = "%temp%\\mod_files\\Dantooine HR"
overwrite = true

[[thisMod.instructions]]
action = "delete"
paths = [
    "%temp%\\mod_files\\Dantooine HR\\DAN_wall03.tpc",
    "%temp%\\mod_files\\Dantooine HR\\DAN_NEW1.tpc",
    "%temp%\\mod_files\\Dantooine HR\\DAN_MWFl.tpc"
]

[[thisMod.instructions]]
action = "move"
source = "%temp%\\mod_files\\Dantooine HR\\"
destination = "%temp%\\Override"

[[thisMod]]
name = "TSLRCM Tweak Pack"
guid = "{C5418549-6B7E-4A8C-8B8E-4AA1BC63C732}"
installOrder = 1
dependencies = []

[[thisMod.instructions]]
action = "extract"
source = "URCMTP 1.3.rar"
destination = "%temp%\\mod_files\\TSLRCM Tweak Pack"
overwrite = true

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""

[[thisMod.instructions]]
action = "run"
path = "%temp%\\mod_files\\TSLPatcher.exe"
arguments = ""
